"""
Data classes for configuration management.
Load configurations via Hydra.

Auto-generated by scripts/generate_configs.py – do not edit by hand.
Re-generate with:  make generate_configs
"""

from dataclasses import dataclass, field
from typing import Any

from hydra.core.config_store import ConfigStore
from omegaconf import MISSING


@dataclass
class AugmentationsConfig:
    name: str = "cpa"
    prob: float = 1.0
    mode: str = "mixup"
    blend: bool = True
    sigma: float = 3.0
    pct_objects_paste: float = 0.5
    max_paste_objects: int = 10
    mosaic: float = 1.0
    mixup: float = 0.0
    cutmix: float = 0.0
    hsv_h: float = 0.015
    hsv_s: float = 0.7
    hsv_v: float = 0.4
    degrees: float = 0.0
    translate: float = 0.1
    scale: float = 0.5
    shear: float = 0.0
    perspective: float = 0.0
    fliplr: float = 0.5
    flipud: float = 0.0
    bgr: float = 0.0


@dataclass
class DatasetConfig:
    name: str = "coco2017"
    root: str = "data.nosync/raw/coco2017"
    train_images: str = "train2017"
    val_images: str = "val2017"
    train_json: str = "annotations/instances_train2017.json"
    val_json: str = "annotations/instances_val2017.json"
    task: str = "segment"
    imgsz: int = 640
    batch_size: int = 12
    num_workers: int = 9
    pin_memory: bool = False
    persistent_workers: bool = True
    cache: bool = False
    coco_eval: bool = True
    augmentations: AugmentationsConfig = field(default_factory=AugmentationsConfig)


@dataclass
class EvaluationConfig:
    run_after_fit: bool = True
    run_epoch_metrics: bool = True
    checkpoint_path: Any = None
    batch_size: Any = None
    conf: float = 0.001
    iou: float = 0.7
    max_det: int = 300
    save_json: bool = True
    plots: bool = False
    split: str = "val"


@dataclass
class ModelsConfig:
    name: str = "configs/models/yolo26/yolo26-seg.yaml"
    architecture: str = "yolo26"
    scale: Any = "n"
    weights: Any = None
    num_loops: int = 12
    embed_dim: int = 128
    num_heads: int = 4
    encoder_layers: int = 2
    decoder_layers: int = 2
    num_queries: int = 20
    patch_size: int = 16
    dropout: float = 0.1
    log_samples: int = 4
    visualization_threshold: float = 0.5


@dataclass
class TrainingConfig:
    mode: str = "fit"
    epochs: int = 100
    accelerator: str = "auto"
    devices: str = "auto"
    precision: str = "auto"
    accumulate_grad_batches: int = 1
    gradient_clip_val: float = 0.0
    optimizer: str = "auto"
    lr0: float = 0.01
    momentum: float = 0.937
    weight_decay: float = 0.0005
    lrf: float = 0.01
    cos_lr: bool = True
    warmup_epochs: float = 3.0
    warmup_momentum: float = 0.8
    warmup_bias_lr: float = 0.1
    nbs: int = 64
    log_every_n_steps: int = 20
    limit_train_batches: float = 1.0
    limit_val_batches: float = 1.0
    resume_from_checkpoint: Any = None


@dataclass
class InstanceTransformerAugConfig:
    experiment_name: str = "instance-transformer-copy-paste"
    dataset: DatasetConfig = field(default_factory=DatasetConfig)
    training: TrainingConfig = field(default_factory=TrainingConfig)
    evaluation: EvaluationConfig = field(default_factory=EvaluationConfig)


@dataclass
class InstanceTransformerNoAugConfig:
    experiment_name: str = "instance-transformer-no-augmentation"
    dataset: DatasetConfig = field(default_factory=DatasetConfig)
    training: TrainingConfig = field(default_factory=TrainingConfig)
    evaluation: EvaluationConfig = field(default_factory=EvaluationConfig)


@dataclass
class WandbConfig:
    project: str = "copy-paste-augmentation"
    entity: Any = None
    group: Any = None
    tags: Any = None
    mode: str = "online"
    log_model: bool = False


@dataclass
class Config:
    dataset: DatasetConfig = MISSING
    models: ModelsConfig = MISSING
    training: TrainingConfig = MISSING
    evaluation: EvaluationConfig = MISSING
    seed: int = 42
    experiment_name: Any = None
    wandb: WandbConfig = field(default_factory=WandbConfig)
    debug: bool = False


def register_configs() -> None:
    """Register structured config schemas with Hydra's ConfigStore.

    Call this once at module level (before @hydra.main) so that
    the schemas are available during config composition:

        from cpa.utils.configs import register_configs
        register_configs()

        @hydra.main(config_path='configs', config_name='default')
        def main(cfg: Config) -> None:
            ...
    """
    cs = ConfigStore.instance()
    cs.store(name="base_config", node=Config)
    cs.store(group="dataset", name="base_dataset", node=DatasetConfig)
    cs.store(group="models", name="base_models", node=ModelsConfig)
    cs.store(group="training", name="base_training", node=TrainingConfig)
    cs.store(group="evaluation", name="base_evaluation", node=EvaluationConfig)
